[package]
name = "obr"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9"
memchr = "2.7"
rustc-hash = "2.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_pipeline_stages"
harness = false
